name: Windows Build and Compile

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        go-version: ['1.22.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies via MSYS2
        uses: msys2/setup-msys2@v2
        with:
          install: |
            mingw64/mingw-w64-x86_64-libusb
            mingw64/mingw-w64-x86_64-pkg-config

      - name: Install additional dependencies
        run: |
          choco install openssl.light -y
          choco install make -y
          choco install 7zip -y
          curl -L "https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip" -o "C:\wpcap-sdk.zip"
          7z x -y "C:\wpcap-sdk.zip" -o"C:\winpcap"

      - name: Add MSYS2 to PATH
        run: echo "D:\a\_temp\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Compile bettercap to EXE
        run: |
          set GO111MODULE=on
          go build -o bettercap.exe

      - name: Upload EXE file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: bettercap-exe
          path: bettercap.exe
